package io.github.wxmyyds.coldfront.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// ── 品牌种子：冷蓝 #0288D1（散热器/冰感） ──
// 如需重新生成完整色板，可用 .agents/skills/md3e/scripts/generate_theme.py

// ── 浅色 ──
val LightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF0061A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD1E4FF),
    onPrimaryContainer = Color(0xFF001D36),
    inversePrimary = Color(0xFF9ECAFF),
    secondary = Color(0xFF535F70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD7E3F7),
    onSecondaryContainer = Color(0xFF101C2B),
    tertiary = Color(0xFF6B5778),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF2DAFF),
    onTertiaryContainer = Color(0xFF251431),
    background = Color(0xFFF6F7FA),
    onBackground = Color(0xFF1A1C1E),
    surface = Color(0xFFF6F7FA),
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFDFE2EB),
    onSurfaceVariant = Color(0xFF42474E),
    surfaceTint = Color(0xFF0061A4),
    inverseSurface = Color(0xFF2F3033),
    inverseOnSurface = Color(0xFFF1F0F4),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF72777F),
    outlineVariant = Color(0xFFC2C6CF),
    scrim = Color(0xFF000000),
    // Brightest light-scheme surface should remain lighter than surface/background.
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainer = Color(0xFFECEEF3),
    surfaceContainerHigh = Color(0xFFE6E8EE),
    surfaceContainerHighest = Color(0xFFE0E3E9),
    surfaceContainerLow = Color(0xFFF2F3F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFD7DADF),
    primaryFixed = Color(0xFFD1E4FF),
    primaryFixedDim = Color(0xFF9ECAFF),
    onPrimaryFixed = Color(0xFF001D36),
    onPrimaryFixedVariant = Color(0xFF00497D),
    secondaryFixed = Color(0xFFD7E3F7),
    secondaryFixedDim = Color(0xFFBBC7DB),
    onSecondaryFixed = Color(0xFF101C2B),
    onSecondaryFixedVariant = Color(0xFF3B4858),
    tertiaryFixed = Color(0xFFF2DAFF),
    tertiaryFixedDim = Color(0xFFD6BEE3),
    onTertiaryFixed = Color(0xFF251431),
    onTertiaryFixedVariant = Color(0xFF523F5F),
)

// ── 深色 ──
val DarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFF9ECAFF),
    onPrimary = Color(0xFF003258),
    primaryContainer = Color(0xFF00497D),
    onPrimaryContainer = Color(0xFFD1E4FF),
    inversePrimary = Color(0xFF0061A4),
    secondary = Color(0xFFBBC7DB),
    onSecondary = Color(0xFF253140),
    secondaryContainer = Color(0xFF3B4858),
    onSecondaryContainer = Color(0xFFD7E3F7),
    tertiary = Color(0xFFD6BEE3),
    onTertiary = Color(0xFF3A2947),
    tertiaryContainer = Color(0xFF523F5F),
    onTertiaryContainer = Color(0xFFF2DAFF),
    background = Color(0xFF0F1114),
    onBackground = Color(0xFFE2E2E6),
    surface = Color(0xFF0F1114),
    onSurface = Color(0xFFE2E2E6),
    surfaceVariant = Color(0xFF42474E),
    onSurfaceVariant = Color(0xFFC2C6CF),
    surfaceTint = Color(0xFF9ECAFF),
    inverseSurface = Color(0xFFE2E2E6),
    inverseOnSurface = Color(0xFF2F3033),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8C9198),
    outlineVariant = Color(0xFF42474E),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF34373C),
    surfaceContainer = Color(0xFF1A1D21),
    surfaceContainerHigh = Color(0xFF25282C),
    surfaceContainerHighest = Color(0xFF303337),
    surfaceContainerLow = Color(0xFF16191C),
    surfaceContainerLowest = Color(0xFF0A0C0F),
    surfaceDim = Color(0xFF0F1114),
    primaryFixed = Color(0xFFD1E4FF),
    primaryFixedDim = Color(0xFF9ECAFF),
    onPrimaryFixed = Color(0xFF001D36),
    onPrimaryFixedVariant = Color(0xFF00497D),
    secondaryFixed = Color(0xFFD7E3F7),
    secondaryFixedDim = Color(0xFFBBC7DB),
    onSecondaryFixed = Color(0xFF101C2B),
    onSecondaryFixedVariant = Color(0xFF3B4858),
    tertiaryFixed = Color(0xFFF2DAFF),
    tertiaryFixedDim = Color(0xFFD6BEE3),
    onTertiaryFixed = Color(0xFF251431),
    onTertiaryFixedVariant = Color(0xFF523F5F),
)
